name: ${DOCKER_NAME}
services:
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
      - "3478:3478/udp"
      - "50000-50100:50000-50100/udp"
    volumes:
      - ../files/volumes/livekit/livekit.yaml:/etc/livekit.yaml:ro
    command: --config /etc/livekit.yaml
    networks:
      default:
      huly_net:
        aliases:
          - livekit
    restart: unless-stopped

  redis:
    image: redis:8.0.2-alpine3.21
    restart: unless-stopped

networks:
  huly_net:
    external: true
    name: huly_net
